name: Build java application
on:
  push:
    branches:
      - master
      - main
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up java and maven
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install package

      - name: Upload the artifact to github
        uses: actions/upload-artifact@v4
        with: 
          name: java-example.war
          path: /home/runner/work/github-actions-practice-2/github-actions-practice-2/target/java-example.war
